### PR TITLE
Pull areas from gr

### PR DESCRIPTION
**Pull request by draffensperger**
This will make the areas pull from global registry when we import the data and also when we fetch a ministry from global registry it will fetch its associated area if we don't have it stored locally.

I wanted to use the new Ruby 2.3 safe navigation operator which caused Rubocop to ask to update Rubocop to 2.3 which then wanted us to use the frozen string comment pragma throughout. In Ruby 3.0 all strings will be frozen by default so this is a good way to prep ourselves for that eventually, but it makes for a lot of code changes in the short run.

### CODE REVIEW

**Comment by twinge** [comment]
The other option would be to just ignore the cop for now (though i'm not opposed to this).

**Comment by draffensperger** [comment]
Yeah, I thought about that, but I think that of any project this is a nice one to try something like that out especially since we haven't deployed it to production yet.

**Comment by draffensperger** [comment]
@Omicron7 / @soberstadt are you guys OK with the frozen strings pragma in all our files `rubocop -a` will add it automatically so we won't need to type them?

One idea I had was for me to do a separate PR for the frozen string stuff and then merge that into this one to make this one easier to review.

**Comment by Omicron7** [comment]
I'm ok with it. I would think ruby would have some way to enable it project wide instead of per file.

**Comment by soberstadt** [comment]
I agree with Brian that it would be nice to be able to do this on the whole project. But I guess you don't really want to do that yet since it's very probable gems don't support it yet. So I'm good with these changes.

**Comment by draffensperger** [comment]
That's a good point Spencer about the gems not supporting it. I hadn't thought of that as a reason for the per-file pragmas.

The way it seems to do it for the whole project is to run `ruby` with `--enable-frozen-string-literal` (see https://wyeworks.com/blog/2015/12/1/immutable-strings-in-ruby-2-dot-3 for some discussion of the pragma and the command line arg).

Since the call to `ruby` is deeper in the stack (ultimately run by `supervisord` in docker container) and because of that issue with gems, @Omicron7 are you OK with the pragmas for now?

If so, I'll do a separate pull request just with the frozen string stuff and then merge that one into this to make this one's actual contentful changes clear.

**Comment by Omicron7** [comment]
:+1: You can do it as a single PR

**Pull request merged**
