### PR TITLE
Model fixes for import script

### PR DESCRIPTION
**Pull request by draffensperger**
These are some validation relaxations and a few other fixes / conveniences for the import script that are outside of the import script itself.

Two that I'm not as sure about are churches without ministries (which do exist in the current SQL server data), and training completions with zero `number_completed`. If those records don't serve a purpose we could just skip the in the data, but these validation relaxations will allow them in.

### CODE REVIEW

**Comment by draffensperger** [comment]
@soberstadt or @Omicron7 does this stuff look OK to you guys?

**Comment by soberstadt** [comment]
@Omicron7 these questions might be better for you or Jon to answer. I think that deleting trainings with zero completions is fine because there is validation code in the existing system to prevent that: https://github.com/GlobalTechnology/gp_SingleBestRecord/blob/master/gp_sbr/Controllers/v5/measurements/user/training_completionController.vb#L97

**Comment by draffensperger** [comment]
Looking at that validation, it uses `< 0` which would prevent actual negatives but allow `0` itself. I don't know enough of the context of the system to know whether a `0` value could be a useful placeholder or just an irrelevant record.

**Comment by soberstadt** [comment]
oh, that true, that's my bad.
For the churches: we can always go back and snuff out those orphans later, but why did you move the name validation? Are there churches with no name? That seems like i should be required still.

**Comment by Omicron7** [comment]
Looks good to me

**Comment by draffensperger** [comment]
Yeah, there are churches with no names:
"Brian Zoetewey: Jon says we need to keep the churches with no name. "Yes. Not sure why they have no name, but the came from Virgil's cookbook."

**Comment by draffensperger** [comment]
I asked Jon about the training completions with zeros. For now let's assume we allow them and later on we can remove them and tighten the validation to not allow user if we want to.

**Pull request merged**
