### PR TITLE
add 'global public' to church secutity options

### PR DESCRIPTION
**Pull request by soberstadt**

### CODE REVIEW

**Comment by soberstadt** [comment]
@jonvellacott it looks like the old api still filters responses based on the 0 level security: https://github.com/GlobalTechnology/gp_SingleBestRecord/blob/master/gp_sbr/Controllers/v5/measurements/user/churchesController.vb#L85
Do you think we should drop that logic and treat those churches a 'private'?

**Comment by Omicron7** [comment]
@soberstadt Did you get sufficient answers from Jon on this one? Is it ready to merge?

**Comment by soberstadt** [comment]
I got no answer from Jon yet. But I think I'm going to try get this merged by the end of the day.

**Comment by soberstadt** [comment]
@Omicron7, I think it is too late to get Jon's opinion in this today. Could you give me a code review on this?

**Comment by Omicron7** [comment]
:+1:

**Pull request merged**
