### PR TITLE
Data import script

### PR DESCRIPTION
**Pull request by draffensperger**
Here's the data import script. Here's what you need to do to get the data properly imported:
- Create the directory `tmp/sql_server_csv_dump` under your `measurements_api` folder e.g. from the folder run `mkdir -p tmp/sql_server_csv_dump]`
- Go to Navicat for SQL Server and select all the tables and click Export. Choose CSV File, for the path, select the `sql_server_csv_dump` folder you just created. Choose to export all fields, then in the additional options choose "Include column titles" and for the "Text Qualifier" select `"`.
- Once the import finishes, go back to the measurements api folder and run `import_from_csv.sh`.
- The output of the import will be saved to a file `tmp/import_results.txt`.
- The import is designed to run against the production global registry since the keys in the SQL server database point to the prod global registry. I have a key from Josh for the prod global registry that is effectively a read-only key (it is for a temporary organization that has read-only access to the production measurements api data).

### CODE REVIEW

**Comment by draffensperger** [comment]
@Omicron7 / @soberstadt you guys OK with me merging this? That will allow me to test out the import in a `stage_console`. I got the import of story images to S3 going. I made one small change to `ImageUploader` to make it put the story images in a more scoped directory (copied code from MPDX).

**Comment by Omicron7** [comment]
@draffensperger Just to clarify, the gr_id keys in the production database point to the production GR, the keys in the stage database point to the staging GR.

**Comment by draffensperger** [comment]
Yeah, that's a good point. I should be able to run this on Jon's staging data. I'll work on doing that.

I do think it would still be nice to get his production data fully into our staging site to do a fully realistic test and to make sure the import didn't miss any important data. But that won't be possible until we can do a refresh of the staging global registry from production.

**Comment by draffensperger** [comment]
@Omicron7 assuming that for now anyway we are only going to test in stage with data from Jon's staging database are you OK with merging this?

**Comment by Omicron7** [comment]
:+1:

**Pull request merged**
