### PR TITLE
Make it easy and secure to run sidekiq web

### PR DESCRIPTION
**Pull request by draffensperger**
To get the sidekiq web for stage/production we'll need to combine this with `run_locally` (and I think map a port) but that should be possible. Once it's merged I'll look into it. Would be nice for us to be able to monitor sidekiq for the API well.

### CODE REVIEW

**Comment by soberstadt** [comment]
:+1: sure

**Comment by draffensperger** [comment]
I actually looked at this a bit more and saw that there is already a `/sidekiq` route which would be more convenient anyway. One of the options for setting up sidekiq web is to use HTTP basic auth which seems like a good idea: https://github.com/mperham/sidekiq/wiki/Monitoring#rails-http-basic-auth-from-routes

The sidekiq web dashboard allows you to modify the state by deleting enqueued jobs, etc. so we should include some type of authentication for it and basic auth seems the easiest (and it's fine as long as we use HTTPS which we will in stage/prod).

**Comment by twinge** [comment]
You can inspect the session at the routing layer to determine if the
currently logged in user should have access to sidekiq:
https://github.com/CruGlobal/missionhub/blob/master/config/routes.rb#L8

**Comment by draffensperger** [comment]
Right, but for the measurements API the authentication is based on tokens and not on a user who has a persistent login to the site like it would be for a traditional Rails app. Are you OK with basic auth for the Sidekiq web UI given that this is a token based API?

**Comment by twinge** [comment]
yeah, totally fine.

**Comment by draffensperger** [comment]
I looked into this a bit more and I think basic auth would actually be pretty annoying to use because you'd either need to remember the password or have it saved in LastPass (and LastPass doesn't work very well with basic auth). A much simpler approach is to just mount Sidekiq web to a secret URL that we could just bookmark but that someone not on the development team wouldn't have access to.

**Comment by draffensperger** [comment]
@soberstadt / @Omicron7 are you guys OK with this approach (having a secret in the URL for sidekiq web so that it's both relatively easy and secure)?

**Comment by soberstadt** [comment]
I'm good with it.

**Comment by Omicron7** [comment]
Works for me.

**Pull request merged**
